message:
  broadcast:
    # Disable broadcasting with empty string or null
    # E.g.:
    # player-packet: ""
    # system: null
    player-packet: "%Player% sent a magic packet includes {jndi:}"
    system: "Somebody sent a chat contains {jndi:}, but we don't say who did this :P"
