message:
  broadcast:
    # Disable broadcasting with empty string or null
    # E.g.:
    # player-packet: ""
    # system: null
    player-packet: "%Player% sent a magic packet include {jndi:}"
    system: "Have somebody sent a {jndi:}, but we don't say who are"
