name: AntiLog4JJNDIExploit
authors:
  - Shiina-Xi-yu
  - Hai-tun
  - Karlatemp
  - Herobrine
description: Have fun with jndi
website: orangemc.moe
version: Nya-1
main: moe.orangemc.shiina_xi_yu.antilog4jjndiexploit.Main
depend:
  - ProtocolLib